const data = [
  {
    title: 'Comfy Store',
    category: 'React',
    icon: 'fab fa-react',
    url: 'https://project-react-store.netlify.app/',
    src: 'https://github.com/JurysR/React-comfy-store',
    img: 'https://github.com/JurysR/portfolio/tree/main/images/thumbnails/comfy-store-react.png',
  },
  {
    title: 'Stock Photos',
    category: 'React',
    icon: 'fab fa-react',
    url: 'https://project-react-stock-photos.netlify.app/',
    src: 'https://github.com/JurysR/React-API-Project-Stock-Photos',
    img: '../images/thumbnails/stock-photos-react.png',
  },
  {
    title: 'Markdown Preview',
    category: 'React',
    icon: 'fab fa-react',
    url: 'https://project-react-markdown-preview.netlify.app/',
    src: 'https://github.com/JurysR/React-Markdown-Preview',
    img: '../images/thumbnails/markdown-preview.png',
  },
  {
    title: 'Grocery Bud',
    category: 'React',
    icon: 'fab fa-react',
    url: 'https://project-react-grocery-bud.netlify.app/',
    src: 'https://github.com/JurysR/React-Grocery-Bud',
    img: '../images/thumbnails/grocery-bud.png',
  },
  {
    title: 'Store',
    category: 'JavaScript',
    icon: 'fab fa-js',
    url: 'https://jurysr.github.io/Comfy-store/',
    src: 'https://github.com/JurysR/Comfy-store',
    img: '../images/thumbnails/comfy-store.png',
  },
  {
    title: 'Cocktails API',
    category: 'JavaScript',
    icon: 'fab fa-js',
    url: 'https://jurysr.github.io/Cocktails/',
    src: 'https://github.com/JurysR/Cocktails',
    img: '../images/thumbnails/cocktails.png',
  },
  {
    title: 'Gallery',
    category: 'JavaScript',
    icon: 'fab fa-js',
    url: 'https://jurysr.github.io/gallery/',
    src: 'https://github.com/JurysR/gallery',
    img: '../images/thumbnails/gallery.png',
  },
  {
    title: 'Coutdown Timer',
    category: 'JavaScript',
    icon: 'fab fa-js',
    url: 'https://jurysr.github.io/Countdown-timer/',
    src: 'https://github.com/JurysR/Countdown-timer',
    img: '../images/thumbnails/countdown-timer.png',
  },
];
export default data;
